on:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: task-runner-launcher
          target: ${{ matrix.target }}
          zip: all
          tar: none
          token: ${{ secrets.GITHUB_TOKEN }}
          checksum: sha256
